pms/blueprints/user/views.py
# coding: utf-8
from flask import Blueprint, render_template, request, redirect, url_for, flash
from pms.blueprints.user.models import User
from flask_login import login_user, logout_user, login_required

from lib.safe_next_url import safe_next_url

from pms.blueprints.user.forms import LoginForm

user = Blueprint('user', __name__, template_folder='templates')


@user.route('/')
def index():
    return redirect(url_for('admin.index'))


@user.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(next=request.args.get('next'))

    if form.validate_on_submit():
        u = User.find_by_identity(request.form.get('identity'))

        if u and u.authenticated(password=request.form.get('password')):

            if login_user(u, remember=request.form.get('remember_me')) and u.is_active():
                next_url = request.form.get('next')
                print(">>redirect next_url: {}".format(next_url))
                if next_url:
                    return redirect(safe_next_url(next_url))
                return redirect(url_for('admin.index'))
            else:
                flash('This account has been disabled.', 'error')
        else:
            flash('Identity or password is incorrect.', 'error')

    return render_template('user/login.html', form=form)


@user.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'success')
    return redirect(url_for('user.login'))

pms/templates/layouts/app.html
{% extends 'layouts/base.html' %}

{% block header %}
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Project name</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Settings</a></li>
          <li><a href="#">Profile</a></li>
          <li><a href="#">Help</a></li>
          {% if not current_user.is_authenticated %}
          <li><a href="{{ url_for('user.login') }}">Login</a></li>
          {% else %}
          <li><a href="{{ url_for('user.logout') }}">Logout</a></li>
          {% endif %}
        </ul>
        <form class="navbar-form navbar-right">
          <input type="text" class="form-control" placeholder="Search...">
        </form>
      </div>
    </div>
  </nav>

{#  <div class="container-fluid">#}
{#    <div class="row">#}
{#      <div class="col-sm-3 col-md-2 sidebar">#}
{#        <ul class="nav nav-sidebar">#}
{#          <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>#}
{#          <li><a href="#">User Management</a></li>#}
{#          <li><a href="#">Analytics</a></li>#}
{#          <li><a href="#">Export</a></li>#}
{#        </ul>#}
{#      </div>#}
{##}
{#      {% block content %}{% endblock %}#}
{#    </div>#}
{#  </div>#}
{% endblock %}

{#{% block footer %}#}
{#    <li><a href="#">Contact</a></li>#}
{#    <li><a href="#">Feedback</a></li>#}
{#    <li><a href="#">Privacy Policy</a></li>#}
{#    <li><a href="#">Terms of Service</a></li>#}
{#    <li><a href="#">FAQ</a></li>#}
{#{% endblock %}#}

pms/templates/layouts/login.html
{% extends 'layouts/base.html' %}

{% block header %}
  <a href="#">
    <img src="{{ url_for('static', filename='images/snake-eyes-large.jpg') }}"
         class="img-responsive center-block md-margin-bottom"
         width="178" height="176" title="Snake Eyes" alt="Snake Eyes"/>
  </a>
{% endblock %}

{% block footer %}
{% endblock %}